name: fullstack-ai-mini-solution

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@database:5432/postgres
    volumes:
      - .:/app
    depends_on:
      - database
    restart: always

  test:
    build: .
    command: pytest tests/
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@database:5432/postgres
      - MODELS_DIR=ML/models/
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - database

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5894:80"
    depends_on:
      - database

  database:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "6741:5432"

volumes:
  postgres_data:
  pgadmin_data: